name: cengodelivery
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_map: ^6.1.0
  open_route_service: ^1.2.4
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  background_fetch: ^1.2.1
  flutter_background_geolocation: ^4.11.1
  provider: ^6.0.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  audioplayers: ^5.0.0
  path_provider: ^2.0.15
  flutter_image_compress: ^2.0.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/data/orders_data.json
    - assets/sounds/camera_shutter.mp3
